# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import user_auth_pb2 as user__auth__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in user_auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserAuthenticationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LogIn = channel.unary_unary(
                '/UserAuthentication/LogIn',
                request_serializer=user__auth__pb2.LogInRequest.SerializeToString,
                response_deserializer=user__auth__pb2.LogInResponse.FromString,
                _registered_method=True)
        self.ValidateJwt = channel.unary_unary(
                '/UserAuthentication/ValidateJwt',
                request_serializer=user__auth__pb2.ValidateJwtRequest.SerializeToString,
                response_deserializer=user__auth__pb2.ValidateJwtResponse.FromString,
                _registered_method=True)
        self.SignUp = channel.unary_unary(
                '/UserAuthentication/SignUp',
                request_serializer=user__auth__pb2.SignUpRequest.SerializeToString,
                response_deserializer=user__auth__pb2.SignUpResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/UserAuthentication/RefreshToken',
                request_serializer=user__auth__pb2.Empty.SerializeToString,
                response_deserializer=user__auth__pb2.LogInResponse.FromString,
                _registered_method=True)
        self.LogOut = channel.unary_unary(
                '/UserAuthentication/LogOut',
                request_serializer=user__auth__pb2.Empty.SerializeToString,
                response_deserializer=user__auth__pb2.LogInResponse.FromString,
                _registered_method=True)


class UserAuthenticationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LogIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateJwt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserAuthenticationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LogIn': grpc.unary_unary_rpc_method_handler(
                    servicer.LogIn,
                    request_deserializer=user__auth__pb2.LogInRequest.FromString,
                    response_serializer=user__auth__pb2.LogInResponse.SerializeToString,
            ),
            'ValidateJwt': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateJwt,
                    request_deserializer=user__auth__pb2.ValidateJwtRequest.FromString,
                    response_serializer=user__auth__pb2.ValidateJwtResponse.SerializeToString,
            ),
            'SignUp': grpc.unary_unary_rpc_method_handler(
                    servicer.SignUp,
                    request_deserializer=user__auth__pb2.SignUpRequest.FromString,
                    response_serializer=user__auth__pb2.SignUpResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=user__auth__pb2.Empty.FromString,
                    response_serializer=user__auth__pb2.LogInResponse.SerializeToString,
            ),
            'LogOut': grpc.unary_unary_rpc_method_handler(
                    servicer.LogOut,
                    request_deserializer=user__auth__pb2.Empty.FromString,
                    response_serializer=user__auth__pb2.LogInResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserAuthentication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UserAuthentication', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserAuthentication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LogIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserAuthentication/LogIn',
            user__auth__pb2.LogInRequest.SerializeToString,
            user__auth__pb2.LogInResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateJwt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserAuthentication/ValidateJwt',
            user__auth__pb2.ValidateJwtRequest.SerializeToString,
            user__auth__pb2.ValidateJwtResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserAuthentication/SignUp',
            user__auth__pb2.SignUpRequest.SerializeToString,
            user__auth__pb2.SignUpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserAuthentication/RefreshToken',
            user__auth__pb2.Empty.SerializeToString,
            user__auth__pb2.LogInResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserAuthentication/LogOut',
            user__auth__pb2.Empty.SerializeToString,
            user__auth__pb2.LogInResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
